import Head from 'next/head'
import Header from '~/components/Index/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex space-x-4">
        <Header />
      </section>
    </div>
  )
}
