import Head from 'next/head'
import Card from '~/components/Global/Card'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card />
      <p className="text-red">12323</p>
      <p className="text-red">12323</p>
      <p className="text-red">12323</p>
      <p className="text-red">12323</p>
      <p className="text-red">12323</p>
      <p className="text-red">12323</p>
      <p className="text-red">12323</p>
      <p className="text-red">12323</p>
      <p className="text-red">12323</p>
      <p className="text-red">12323</p>
    </div>
  )
}
